INSERT INTO CARS (ID, VIN, MANUFACTURER, MODEL, YEAR, COLOR)
VALUES (0, '3K096I98581DHSNUP', 'Volkswagen', 'Tiguan', 2019, 'BLUE');
INSERT INTO CARS (ID, VIN, MANUFACTURER, MODEL, YEAR, COLOR)
VALUES (1, 'ZM8G7BEUQZ97IH46V', 'Peugeot', 'Rifter', 2019, 'Red');
INSERT INTO CARS (ID, VIN, MANUFACTURER, MODEL, YEAR, COLOR)
VALUES (2, 'RKXVNNIHLVVZOUB4M', 'Ford', 'Fusion', 2018, 'White');
INSERT INTO CARS (ID, VIN, MANUFACTURER, MODEL, YEAR, COLOR)
VALUES (3, 'HKNDGS7CU31E9Z7JW', 'Toyota', 'RAV4', 2018, 'Silver');
INSERT INTO CARS (ID, VIN, MANUFACTURER, MODEL, YEAR, COLOR)
VALUES (4, 'DAM41UDN3CHU2WVF6', 'Volvo', 'V60', 2019, 'Gray');
INSERT INTO CARS (ID, VIN, MANUFACTURER, MODEL, YEAR, COLOR)
VALUES (5, 'DAM41UDN3CHU2WVF6', 'Volvo', 'V60 Cross Country', 2019, 'Gray');

ALTER TABLE CUSTOMERS MODIFY COLUMN PHONE_NUMBER VARCHAR(40)

INSERT INTO CUSTOMERS (ID, CUSTOMER_ID, NAME, PHONE_NUMBER, `e-mail`, ADRESS, CITY, STATE_OR_PROVINCE, COUNTRY, POSTAL_CODE)
VALUES (0, '10001', 'Pablo Picasso', '+34 636176382', '-', 'Paseo de la Chopera, 14', 'Madrid', 'Madrid', 'Spain', 28045)
INSERT INTO CUSTOMERS (ID, CUSTOMER_ID, NAME, PHONE_NUMBER, `e-mail`, ADRESS, CITY, STATE_OR_PROVINCE, COUNTRY, POSTAL_CODE)
VALUES (1, '20001', 'Hedy Lamarr', '+43 1 514442250', '-', 'Weiglgasse 10', 'Viena', 'Vienna', 'Austria', 1150)
INSERT INTO CUSTOMERS (ID, CUSTOMER_ID, NAME, PHONE_NUMBER, `e-mail`, ADRESS, CITY, STATE_OR_PROVINCE, COUNTRY, POSTAL_CODE)
VALUES (2, '30001', 'Katherine Johnson', '++1 202 358 0000', '-', '300 E St SW', 'Washington, DC', 'Washington', 'United States', 20546)

INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (0, '00001', 'Petey Cruiser', 'Madrid');
INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (1, '00002', 'Anna Sthesia', 'Barcelona');
INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (2, '00003', 'Paul Molive', 'Berlin');
INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (3, '00004', 'Gail Forcewind', 'Paris');
INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (4, '00005', 'Paige Turner', 'Mimia');
INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (5, '00006', 'Bob Frapples', 'Mexico City');
INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (6, '00007', 'Walter Melon', 'Amsterdam');
INSERT INTO SALES_PERSONS (ID, STAFF_ID, NAME, STORE)
VALUES (7, '00008', 'Shonda Leer', 'São Paulo')

INSERT INTO INVOICES (ID, INVOICE_NUMBER, DATE, CARS_ID, CUSTOMERS_ID, SALES_PERSONS_ID)
VALUES (0, '852399038', '2018-08-22', 0, 1, 3)
INSERT INTO INVOICES (ID, INVOICE_NUMBER, DATE, CARS_ID, CUSTOMERS_ID, SALES_PERSONS_ID)
VALUES (1, '731166526', '2018-12-31', 3, 0, 5)
INSERT INTO INVOICES (ID, INVOICE_NUMBER, DATE, CARS_ID, CUSTOMERS_ID, SALES_PERSONS_ID)
VALUES (2, '271135104', '2019-01-22', 2, 2, 7)

ALTER TABLE INVOICES DROP COLUMN INVOICE_ID