update customer
set Email='ppicasso@gmail.com'
where ID=0;
update customer
set Email='lamarr_hd@hollywood.com'
where ID=1; 
update customer
set Email='hello@nasa.gov'
where ID=2;
update salesperson
set Store='Miami'
where ID=4;
